language: python
python:
  - "3.7"

install:
  - pip install .
  - pip install torch

before_script:
  - pip install -r test-requirements.txt
  - coverage run -m pytest
script:
  - pytest
after_success:
  - coveralls